[package]
name = "rknpu-exporter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prometheus-client = "0.22.0"
regex = "1.10.2"
rocket = "0.5.0-rc.4"
